version: '3'

services:
  syncthing:
    image: syncthing/syncthing:latest
    ports:
      - "8384:8384"
      - "22000:22000"
    env_file: 
      - "./.env"
    volumes:
      - "${BACKUP_PATH}:/var/syncthing"
    restart: unless-stopped
